package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

import javafx.scene.control.RadioButton;

import javafx.scene.control.PasswordField;

public class mainformController {
	@FXML
	private Button clickMeBtn;
	@FXML
	private TextField userNameTf;
	@FXML
	private RadioButton stayLoginRB;
	@FXML
	private PasswordField passwordTf;

	// Event Listener on Button[#clickMeBtn].onAction
	@FXML
	public void onclickbtn(ActionEvent event) {
		// TODO Autogenerated
		Stage mainPanel = (Stage) userNameTf.getScene().getWindow();
		String username =  userNameTf.getText();
		mainPanel.setTitle(username);
	}
}
